### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by luiseherrera** [troldal/Zippy#1]
Hi,

    I've been struggling to make a clean install and up to now I can not successfully install the library, please can you specify and add a brief of how to do it.

BTW: I've CMake(3.16.2), minizip, make(3.81), gcc(8) and g++(8) installed on my computer.

My intention is to install your 'openXLSX' library as well, but Zippy is a required for.

Thank you.

**Comment by troldal** [comment]
Hi @luiseherrera.

Zippy is bundled with OpenXLSX, so there is no need to install it separately.

**Comment by luiseherrera** [comment]
Hi @troldal,

    Thank you for your quickly response, even though can you guide me through the process of how to manually install it?.

Regards.
